config/routes.rb
Rails.application.routes.draw do
  root to: 'site#home'
  
  get '/home' => 'site#home'
  get '/become_a_host' => 'site#become_a_host'
  get '/help' => 'site#help'
  get '/signup' => 'site#signup'
  get '/login' => 'site#login'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirbnbCloneWithRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="/home"><%= image_tag "logo.png" %></a>
     </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", home_path %></li>
          <li><%= link_to "Become a host", become_a_host_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        </ul>
      </div>
    </div>
  </nav>


<%= yield %>


<div class="container container-brand-dark">
  <footer class="footer center">
    <div class="row">
    <div class="col-md-3 col-md-offset-1">
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Español
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><a href="#">English</a></li>
          <li><a href="#">French</a></li>
          <li><a href="#">German</a></li>
          <li><a href="#">Greek</a></li>
          <li><a href="#">Italian</a></li>
          <li><a href="#">Russian</a></li>
        </ul>
      </div>
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          EUR
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><a href="#">GBP</a></li>
          <li><a href="#">HKD</a></li>
          <li><a href="#">HRK</a></li>
          <li><a href="#">HUF</a></li>
          <li><a href="#">IDR</a></li>
          <li><a href="#">ILS</a></li>
        </ul>
      </div>
    </div>
    <div class="col-md-2 col-md-offset-1 hide-sm">
      <h5>Company</h5>
      <ul class="list-layout">
        <li><a href="#" class="link-contrast">Information</a></li>
        <li><a href="#" class="link-contrast">Jobs</a></li>
        <li><a href="#" class="link-contrast">Press</a></li>
        <li><a href="#" class="link-contrast">BLog</a></li>
        <li><a href="#" class="link-contrast">Help</a></li>
        <li><a href="#" class="link-contrast">Policy</a></li>
        <li><a href="#" class="link-contrast">Response to whatever</a></li>
        <li><a href="#" class="link-contrast">Terms and conditions</a></li>
      </ul>
    </div>
    <div class="col-md-2 hide-sm">
      <h5>Discover Airbnb</h5>
      <ul class="list-layout">
        <li><a href="#" class="link-contrast">Trust and security</a></li>
        <li><a href="#" class="link-contrast">Invite your friends</a></li>
        <li><a href="#" class="link-contrast">Airbnb selection</a></li>
        <li><a href="#" class="link-contrast">Mobile app</a></li>
        <li><a href="#" class="link-contrast">Support New York City</a></li>
        <li><a href="#" class="link-contrast">Business travel</a></li>
        <li><a href="#" class="link-contrast">Sitemap</a></li>
      </ul>
    </div>
    <div class="col-md-2 hide-sm">
      <h5>Hosting</h5>
      <ul class="list-layout">
        <li><a href="#" class="link-contrast">Reasons to host</a></li>
        <li><a href="#" class="link-contrast">Hospitality</a></li>
        <li><a href="#" class="link-contrast">Be a responsible host</a></li>
        <li><a href="#" class="link-contrast">Home security</a></li>
      </ul>
    </div>
  </div>
  <hr>
    <div class="col-md-12 ">

      <div class="social-icons text-center">
        <h5>Follow us:</h5>
        <ul class="list-layout list-inline">
          <li><a href="#"><%= image_tag "facebook.png" %></a></li>
          <li><a href="#"><%= image_tag "twitter.png" %></a></li>
          <li><a href="#"><%= image_tag "linkedin.png" %></a></li>
          <li><a href="#"><%= image_tag "vimeo.png" %></a></li>
          <li><a href="#"><%= image_tag "pinterest.png" %></a></li>
        </ul>
      </div>
    </div>
  </footer>
  </div>

</body>
</html>

app/views/site/_contact_form.html.erb
<form action="/contacts" method="POST">
  <div>
    <label for="contact_name">Name</label>
    <input type="text" name="contact[name]" id="contact_name">
  </div>

  <div>
    <label for="contact_address">Address</label>
    <textarea name="contact[address]" id="contact_address"></textarea>
  </div>

  <div>
    <label for="phone_number">Phone number</label>
    <input type="tel" name="contact[phone_number]" id="phone_number">
  </div>

  <div>
    <label for="contact_email">Email</label>
    <input type="email" name="contact[email]" id="contact_email">
  </div>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <button type="submit">Sign me up</button>
</form>

app/views/site/become_a_host.html.erb
<h1>Become a host</h1>

<div class="contact-form">
  <%= render "contact_form" %>
</div>

app/views/site/help.html.erb
<h1>Help</h1>

<div class="contact-form">
  <%= render "contact_form" %>
</div>

app/views/site/home.html.erb
<div class="container-fluid">
  <div class="row hero text-center">
    <h1 class="tagline">HOME SWEET HOME</h1>
    <p class="lead">Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
    <a class="btn btn-default" href="#" role="button">How does it work</a>
  </div>

    <div class="content col-md-8 col-md-offset-2"
    <!-- start slipsum code -->
    <p class="lead">Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends. </p>

    <p>Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends. </p>

    <p>The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee. </p>

    <p>Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'? </p>

    <p>Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they're actually proud of that shit.  </p>

    <p>Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass. </p>

    <p>My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand? </p>

    <p>Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they're actually proud of that shit.  </p>
    </div>
</div>

app/views/site/login.html.erb
<!-- app/views/contacts/new.html.erb -->
<h1>Login</h1>

<form action="/contacts" method="POST">
  <div>
    <label for="contact_email">Email</label>
    <input type="email" name="contact[email]" id="contact_email">
  </div>

  <div>
    <label for="password">Address</label>
    <textarea name="contact[address]" id="password"></textarea>
  </div>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <button type="submit">Login</button>
</form>

app/views/site/signup.html.erb
<h1>Sign up</h1>

<div class="contact-form">
  <%= render "contact_form" %>
</div>